[versions]
jackson = "3.2.1"
kotest = "6.2.4"
microsoft-json-date-parser = "0.9.3"
mschout-conventions = "0.7.1"

[libraries]
jackson-core = { module = "tools.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
microsoft-json-date-parser = { module = "io.github.mschout:microsoft-json-date-parser", version.ref = "microsoft-json-date-parser" }

[plugins]
mschout-all-conventions = { id = "io.github.mschout.all-conventions", version.ref = "mschout-conventions" }
mschout-maven-publish-conventions = { id = "io.github.mschout.maven-publish-conventions", version.ref = "mschout-conventions" }
